### ISSUE TITLE
Размер шрифта карточек

### ISSUE THREAD

**Issue by pasha-liubetski** [linkasu/linka.looks-electron#81]
Очень не хватает возможности регулировать размер шрифта подписей к карточкам. Многим детям сложно разбирать мелкие подписи, и было бы проще, если бы можно было в настройках программы сделать шрифт полужирным и выбрать его размер.

В качестве workaround мы пользуемся пунктами меню `View → Zoom In`, `View → Zoom Out` и `View → Actual Size`, но было бы удобнее, если бы можно было менять размер шрифта в настройках.

В файле `src/frontend/components/SetGridButton.vue` можно менять шрифт подписей: <https://github.com/linkasu/linka.looks-electron/blob/32cc8814bfc272d386f351224f010a3662ad5895/src/frontend/components/SetGridButton.vue#L169C8-L169C8>

Пример правок CSS:
```css
.text {
  height: 200%;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 100%;
  font-size: 1.7em;
  font-weight: bold;
}
```
Карточки выглядят как на скриншоте:

![2023-12-15-150046_1920x1048_scrot](https://github.com/linkasu/linka.looks-electron/assets/110045133/2f9faed7-f764-4201-b4f9-3f11ffd72f5d)
